# Generated by Django 4.1.3 on 2022-11-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telefone', models.CharField(max_length=11, verbose_name='telefone')),
            ],
        ),
    ]
